# Generated by Django 6.0.2 on 2026-04-22 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('IT', 'Information Technology')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='cgpa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='register_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
